name: Chrome UI Tests

on:
  workflow_dispatch:

jobs:
  chrome-ui-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-22.17.0-chrome-138.0.7204.157-1-ff-140.0.4-edge-138.0.3351.83-1
    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ping my API
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api.onrender.com/

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: 'https://samuraibs-web.onrender.com'
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/**/*.cy.js  # ajuste conforme o nome dos seus arquivos
          record: true
          parallel: true
          group: 'UI - Chrome'
        env:
          TZ: America/Sao_Paulo
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
