name: Chrome UI Tests

on:
  workflow_dispatch:

jobs:
  chrome-ui-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107-ff107  # CORRIGIDO

    strategy:
      fail-fast: false
      matrix:
        containers: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ping my API
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api.onrender.com/

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: 'https://samuraibs-web.onrender.com'
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/**/*.cy.js  # ajuste se usar .spec.js
        env:
          TZ: America/Sao_Paulo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
